version: '3.8'

services:
  db:
    image: postgres:17
    container_name: dev_forum_db
    environment:
      POSTGRES_DB: dev_forum
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
    ports:
      - "5432:5432"
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped